### PR TITLE
Import FindMatlab from upstream CMake

### PR DESCRIPTION
**Pull request by jamiesnape**
As discussed F2F. PTAL @david-german-tri.

### CODE REVIEW

**Comment by david-german-tri** [comment]
Does this for some reason not require the same modifications as RobotLocomotion/drake#3586?

**Comment by jamiesnape** [comment]
The only modifications involved `matlab_add_unit_test`, so they are not needed.

**Comment by jamiesnape** [comment]
Thanks. I will post a PR to drake shortly.

**Comment by jamiesnape** [comment]
RobotLocomotion/drake#3624

**Pull request merged**
